using PactNet;
using PactNet.Output.Xunit;
using PactNet.Verifier;
using DeviceApi.Provider.Tests.Config;
using DeviceApi.Provider.Tests.Fixtures;
using Xunit;
using Xunit.Abstractions;

namespace DeviceApi.Provider.Tests.Tests;

/// <summary>
/// Provider-side Pact verification tests.
///
/// Workflow:
///   1. <see cref="DeviceApiProviderFixture"/> boots the real DeviceApi on a
///      free port using <see cref="ApiBootstrap.CreateWebApplication"/>.
///   2. The PactNet verifier replays every interaction from the pact file
///      (generated by <c>DeviceApi.Consumer.Tests</c>) against the live API.
///   3. Any deviation between the consumer contract and the provider response
///      causes this test to fail.
///
/// Run order enforced by <c>run-pact-tests.ps1</c>:
///   Consumer tests   →  contracts/DeviceApi-Consumer-DeviceApi.json
///   Provider tests   →  verify the file against the running API
/// </summary>
[Collection("Provider Pact Verification")]
public sealed class DeviceApiProviderTests : IClassFixture<DeviceApiProviderFixture>
{
    private readonly DeviceApiProviderFixture _fixture;
    private readonly ITestOutputHelper        _output;

    public DeviceApiProviderTests(DeviceApiProviderFixture fixture, ITestOutputHelper output)
    {
        _fixture = fixture;
        _output  = output;
    }

    /// <summary>
    /// Replays all consumer interactions defined in the pact file against the
    /// running provider and asserts every one passes.
    /// </summary>
    [Fact]
    [Trait("Category", "PactVerification")]
    public void Provider_Satisfies_All_ConsumerPactInteractions()
    {
        var pactFile = new FileInfo(PactConstants.PactFilePath);

        Assert.True(
            pactFile.Exists,
            $"Pact file not found at: {pactFile.FullName}\n" +
            "Run DeviceApi.Consumer.Tests first to generate it.");

        var config = new PactVerifierConfig
        {
            LogLevel  = PactLogLevel.Information,
            Outputters = new[] { new XunitOutput(_output) }
        };

        var providerStateUri = new Uri(_fixture.ServerUri, PactConstants.ProviderStatesPath);

        new PactVerifier(PactConstants.ProviderName, config)
            .WithHttpEndpoint(_fixture.ServerUri)
            .WithFileSource(pactFile)
            .WithProviderStateUrl(providerStateUri)
            .Verify();
    }
}
