using System.Text.Json;
using System.Text.Json.Nodes;
using FluentAssertions;
using DeviceApi.Provider.Tests.Config;
using DeviceApi.Provider.Tests.Fixtures;
using Xunit;
using Xunit.Abstractions;

namespace DeviceApi.Provider.Tests.Tests;

/// <summary>
/// Swagger endpoint coverage gate.
///
/// Problem solved:
///   A new endpoint added to DeviceApi may be missed by consumers — they won't
///   write a consumer pact test unless they know the endpoint exists.
///
/// How it works:
///   1. Downloads the live swagger.json from the running API.
///   2. Extracts every path + HTTP method combination (endpoint operations).
///   3. Reads the pact file generated by consumer tests.
///   4. Checks that every swagger operation is referenced by at least one
///      pact interaction.
///   5. FAILS with an actionable message for any uncovered endpoint, listing:
///      - Which operation is missing.
///      - Which consumer teams to notify (from contracts/consumers.json).
///      - Where to add the consumer test stub.
///      - The path of the auto-generated skeleton (Generated/ folder).
///
/// Integration with SwaggerPactGenerator:
///   The <c>run-pact-tests.ps1</c> script runs
///   <c>tools/SwaggerPactGenerator</c> before this test suite. For every
///   uncovered swagger operation the generator creates a skeleton consumer
///   test stub in
///   <c>tests/DeviceApi.Consumer.Tests/Generated/</c>.
///   The consumer team fills in the stub and moves it to Contracts/.
///
/// Self-bootstrapping:
///   If no pact file exists yet, this test is skipped (first-run scenario).
/// </summary>
[Collection("Provider Pact Verification")]
public sealed class SwaggerCoverageTests : IClassFixture<DeviceApiProviderFixture>
{
    private readonly DeviceApiProviderFixture _fixture;
    private readonly ITestOutputHelper        _output;

    public SwaggerCoverageTests(DeviceApiProviderFixture fixture, ITestOutputHelper output)
    {
        _fixture = fixture;
        _output  = output;
    }

    /// <summary>
    /// Verifies that every swagger operation is covered by at least one
    /// consumer pact interaction.
    /// </summary>
    [Fact]
    [Trait("Category", "SwaggerCoveragGate")]
    public async Task AllSwaggerEndpoints_AreCoveredByConsumerPacts()
    {
        // ── 1. Skip gracefully on first run (no pact file yet) ────────────────
        if (!File.Exists(PactConstants.PactFilePath))
        {
            _output.WriteLine(
                "[SKIP] No pact file found. Run DeviceApi.Consumer.Tests first.");
            return;
        }

        // ── 2. Fetch live swagger.json ─────────────────────────────────────────
        using var client          = new HttpClient { BaseAddress = _fixture.ServerUri };
        var       swaggerJson     = await client.GetStringAsync("/swagger/v1/swagger.json");
        var       swaggerOps      = ExtractOperations(swaggerJson);

        // ── 3. Read pact interactions ──────────────────────────────────────────
        var pactJson              = await File.ReadAllTextAsync(PactConstants.PactFilePath);
        var coveredOps            = ExtractPactInteractionPaths(pactJson);

        // ── 4. Find uncovered operations ──────────────────────────────────────
        var uncovered = swaggerOps
            .Where(op => !coveredOps.Any(c =>
                string.Equals(c.Method, op.Method, StringComparison.OrdinalIgnoreCase)
                && PathsMatch(c.Path, op.Path)))
            .ToList();

        if (uncovered.Count == 0)
        {
            _output.WriteLine($"[OK] All {swaggerOps.Count} swagger operation(s) are covered by consumer pacts.");
            return;
        }

        // ── 5. Report uncovered operations ────────────────────────────────────
        var consumers    = LoadConsumerRegistry();
        var generatedDir = Path.GetFullPath(Path.Combine(
            PactConstants.PactDir, "..", "tests",
            "DeviceApi.Consumer.Tests", "Generated"));

        _output.WriteLine("╔══════════════════════════════════════════════════════════════════╗");
        _output.WriteLine("║  UNCOVERED SWAGGER ENDPOINTS — CONSUMER PACTS REQUIRED          ║");
        _output.WriteLine("╠══════════════════════════════════════════════════════════════════╣");
        _output.WriteLine("║  The following swagger operations have NO consumer pact          ║");
        _output.WriteLine("║  interaction. Consumer teams must add contract tests.            ║");
        _output.WriteLine("╠══════════════════════════════════════════════════════════════════╣");

        foreach (var op in uncovered)
        {
            _output.WriteLine($"║  {op.Method.ToUpper(),-8} {op.Path,-55} ║");
        }

        _output.WriteLine("╠══════════════════════════════════════════════════════════════════╣");
        _output.WriteLine("║  Consumer teams to notify:                                       ║");

        foreach (var consumer in consumers)
        {
            _output.WriteLine($"║   → {consumer.Name} | {consumer.Team} | {consumer.Contact,-30} ║");
        }

        _output.WriteLine("╠══════════════════════════════════════════════════════════════════╣");
        _output.WriteLine("║  Action:                                                         ║");
        _output.WriteLine("║  1. Skeleton test stubs are in:                                  ║");
        _output.WriteLine($"║     {generatedDir.PadRight(63)} ║");
        _output.WriteLine("║  2. Review the stub, fill in assertions, move to Contracts/.     ║");
        _output.WriteLine("║  3. Re-run: run-pact-tests.ps1                                   ║");
        _output.WriteLine("╚══════════════════════════════════════════════════════════════════╝");

        uncovered.Should().BeEmpty(
            because: "every swagger operation must have at least one consumer pact " +
                     "interaction. Use the generated stubs in Generated/ to create them.");
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private record ApiOperation(string Method, string Path);

    /// <summary>
    /// Extracts all path + method combinations from a swagger JSON document.
    /// </summary>
    private static List<ApiOperation> ExtractOperations(string swaggerJson)
    {
        var node  = JsonNode.Parse(swaggerJson)!;
        var paths = node["paths"]?.AsObject();
        var ops   = new List<ApiOperation>();

        if (paths is null)
            return ops;

        foreach (var (path, methods) in paths)
        {
            foreach (var (method, _) in methods!.AsObject())
            {
                // Only include HTTP verbs (skip x-* extensions)
                if (IsHttpVerb(method))
                    ops.Add(new ApiOperation(method, path));
            }
        }

        return ops;
    }

    /// <summary>
    /// Extracts the request path + method from every pact interaction.
    /// </summary>
    private static List<ApiOperation> ExtractPactInteractionPaths(string pactJson)
    {
        var node         = JsonNode.Parse(pactJson)!;
        var interactions = node["interactions"]?.AsArray();
        var ops          = new List<ApiOperation>();

        if (interactions is null)
            return ops;

        foreach (var interaction in interactions)
        {
            var request = interaction?["request"];
            var method  = request?["method"]?.GetValue<string>();
            var path    = request?["path"]?.GetValue<string>();

            if (method is not null && path is not null)
                ops.Add(new ApiOperation(method, path));
        }

        return ops;
    }

    /// <summary>
    /// Normalises paths for comparison — strips query strings and trailing slashes.
    /// </summary>
    private static bool PathsMatch(string pactPath, string swaggerPath)
    {
        // Trim query strings from pact path
        var cleanPact    = pactPath.Split('?')[0].TrimEnd('/');
        // Swagger uses {param} placeholders — for matching purposes compare literal segments
        var cleanSwagger = swaggerPath.TrimEnd('/');

        return string.Equals(cleanPact, cleanSwagger, StringComparison.OrdinalIgnoreCase);
    }

    private static bool IsHttpVerb(string method) =>
        method is "get" or "post" or "put" or "patch" or "delete" or "head" or "options";

    private static List<ConsumerRegistryEntry> LoadConsumerRegistry()
    {
        if (!File.Exists(PactConstants.ConsumersRegistryPath))
            return [];

        try
        {
            var json = File.ReadAllText(PactConstants.ConsumersRegistryPath);
            var doc  = JsonSerializer.Deserialize<ConsumerRegistry>(json,
                new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
            return doc?.Consumers ?? [];
        }
        catch
        {
            return [];
        }
    }

    private sealed record ConsumerRegistry(List<ConsumerRegistryEntry> Consumers);
    private sealed record ConsumerRegistryEntry(
        string Name,
        string Team,
        string Contact,
        string Slack,
        string PactFile);
}
