using System.Text.Json;
using System.Text.Json.Nodes;
using FluentAssertions;
using DeviceApi.Provider.Tests.Config;
using DeviceApi.Provider.Tests.Fixtures;
using Xunit;
using Xunit.Abstractions;

namespace DeviceApi.Provider.Tests.Tests;

/// <summary>
/// Response field coverage gate.
///
/// Problem solved:
///   <see cref="SwaggerCoverageTests"/> verifies that every swagger
///   <em>endpoint</em> (path + HTTP method) has at least one pact interaction.
///   It does NOT check that every <em>response field</em> defined by the
///   swagger schema is asserted by the consumer.
///
///   When a new field is added to a response model (e.g. <c>NewPartNumber</c>)
///   the consumer pact may continue to pass because pact is consumer-driven and
///   the provider is allowed to return extra fields.  This leaves the new field
///   completely uncovered — no pact guarantees it will ever be delivered
///   correctly to the consumer.
///
/// What this test does:
///   1. Downloads the live swagger.json from the running API.
///   2. For every operation that returns a 2xx JSON response with a schema:
///      a. Resolves the schema (following <c>$ref</c> chains).
///      b. Collects all top-level property names.
///   3. Reads the pact file generated by consumer tests.
///   4. For each matching interaction (same path + method, 2xx status):
///      Collects every field that is either:
///        • present as a key in <c>response.body.content</c>, OR
///        • present as <c>$.fieldName</c> in <c>response.matchingRules.body</c>
///   5. FAILS for any swagger property that has no pact coverage, listing:
///      - The offending field and endpoint.
///      - Which consumer teams to notify.
///      - Where to add the missing assertion.
///
/// Self-bootstrapping:
///   If no pact file exists yet the test is skipped (first-run scenario).
/// </summary>
[Collection("Provider Pact Verification")]
public sealed class SwaggerResponseFieldCoverageTests : IClassFixture<DeviceApiProviderFixture>
{
    private readonly DeviceApiProviderFixture _fixture;
    private readonly ITestOutputHelper        _output;

    public SwaggerResponseFieldCoverageTests(DeviceApiProviderFixture fixture, ITestOutputHelper output)
    {
        _fixture = fixture;
        _output  = output;
    }

    [Fact]
    [Trait("Category", "SwaggerResponseFieldCoverage")]
    public async Task AllSwaggerResponseFields_AreCoveredByConsumerPacts()
    {
        // ── 1. Skip gracefully on first run ───────────────────────────────────
        if (!File.Exists(PactConstants.PactFilePath))
        {
            _output.WriteLine("[SKIP] No pact file found. Run DeviceApi.Consumer.Tests first.");
            return;
        }

        // ── 2. Fetch live swagger.json ────────────────────────────────────────
        using var client      = new HttpClient { BaseAddress = _fixture.ServerUri };
        var       swaggerJson = await client.GetStringAsync("/swagger/v1/swagger.json");
        var       swagger     = JsonNode.Parse(swaggerJson)!;

        // ── 3. Read pact interactions ─────────────────────────────────────────
        var pactJson     = await File.ReadAllTextAsync(PactConstants.PactFilePath);
        var pact         = JsonNode.Parse(pactJson)!;
        var interactions = pact["interactions"]?.AsArray() ?? [];

        // ── 4. Check each swagger operation ──────────────────────────────────
        var missing = new List<string>();

        var paths = swagger["paths"]?.AsObject();
        if (paths is null)
        {
            _output.WriteLine("[SKIP] Swagger has no paths.");
            return;
        }

        foreach (var (swaggerPath, pathItem) in paths)
        {
            foreach (var (method, operation) in pathItem!.AsObject())
            {
                if (!IsHttpVerb(method)) continue;

                // Collect all 2xx response schema properties for this operation
                var schemaFields = Get2xxResponseFields(operation!, swagger);
                if (schemaFields.Count == 0) continue;

                // Collect fields covered in pact for this path+method (2xx)
                var coveredFields = GetPactCoveredFields(interactions, method, swaggerPath);

                // Find schema fields not covered by pact
                var uncoveredFields = schemaFields
                    .Where(f => !coveredFields.Contains(f, StringComparer.OrdinalIgnoreCase))
                    .ToList();

                if (uncoveredFields.Count == 0) continue;

                foreach (var field in uncoveredFields)
                {
                    missing.Add($"{method.ToUpper()} {swaggerPath}  →  response field '{field}' not asserted in any pact interaction");
                }
            }
        }

        if (missing.Count == 0)
        {
            _output.WriteLine("[OK] All swagger response fields are covered by at least one pact interaction.");
            return;
        }

        // ── 5. Report missing coverage ────────────────────────────────────────
        var consumers = LoadConsumerRegistry();

        _output.WriteLine("╔══════════════════════════════════════════════════════════════════╗");
        _output.WriteLine("║  SWAGGER RESPONSE FIELDS NOT COVERED BY PACT — ACTION REQUIRED  ║");
        _output.WriteLine("╠══════════════════════════════════════════════════════════════════╣");
        _output.WriteLine("║  The swagger response schema defines fields that are absent from ║");
        _output.WriteLine("║  every consumer pact interaction for that endpoint.              ║");
        _output.WriteLine("║  The consumer has NO contract guaranteeing these fields.         ║");
        _output.WriteLine("╠══════════════════════════════════════════════════════════════════╣");

        foreach (var entry in missing)
            _output.WriteLine($"║  {entry.PadRight(66)} ║");

        _output.WriteLine("╠══════════════════════════════════════════════════════════════════╣");
        _output.WriteLine("║  Consumer teams to notify:                                       ║");
        foreach (var consumer in consumers)
            _output.WriteLine($"║   → {consumer.Name} | {consumer.Team} | {consumer.Contact,-30} ║");

        _output.WriteLine("╠══════════════════════════════════════════════════════════════════╣");
        _output.WriteLine("║  How to fix:                                                     ║");
        _output.WriteLine("║  1. Open tests/DeviceApi.Consumer.Tests/Contracts/               ║");
        _output.WriteLine("║  2. Add the missing field to the relevant With() body assertion. ║");
        _output.WriteLine("║  3. Re-run consumer tests to regenerate the pact file.           ║");
        _output.WriteLine("║  4. Re-run provider tests — this gate will then pass.            ║");
        _output.WriteLine("╚══════════════════════════════════════════════════════════════════╝");

        missing.Should().BeEmpty(
            because: "every field in the swagger response schema must be asserted by at " +
                     "least one consumer pact interaction. See the list above for details.");
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /// <summary>
    /// Returns the set of top-level property names defined in any 2xx
    /// application/json response schema for the given swagger operation node.
    /// Follows <c>$ref</c> pointers into <c>components/schemas</c>.
    /// </summary>
    private static HashSet<string> Get2xxResponseFields(JsonNode operation, JsonNode swagger)
    {
        var fields    = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var responses = operation["responses"]?.AsObject();
        if (responses is null) return fields;

        foreach (var (statusCode, responseNode) in responses)
        {
            if (!Is2xx(statusCode)) continue;

            var schemaNode = responseNode?["content"]?["application/json"]?["schema"];
            if (schemaNode is null) continue;

            var resolved = ResolveRef(schemaNode, swagger);
            var props    = resolved?["properties"]?.AsObject();
            if (props is null) continue;

            foreach (var (propName, _) in props)
                fields.Add(propName);
        }

        return fields;
    }

    /// <summary>
    /// Returns the set of response body field names that are asserted in pact
    /// interactions for the given path + method combination with a 2xx response.
    /// Collects fields from both <c>response.body.content</c> keys and
    /// <c>response.matchingRules.body</c> <c>$.fieldName</c> keys.
    /// </summary>
    private static HashSet<string> GetPactCoveredFields(
        JsonArray interactions, string method, string path)
    {
        var covered = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var interaction in interactions)
        {
            var request = interaction?["request"];
            if (request is null) continue;

            var iMethod = request["method"]?.GetValue<string>() ?? "";
            var iPath   = request["path"]?.GetValue<string>() ?? "";

            if (!string.Equals(iMethod, method, StringComparison.OrdinalIgnoreCase)) continue;
            if (!PathsMatch(iPath, path)) continue;

            var response = interaction?["response"];
            if (response is null) continue;

            var status = response["status"]?.GetValue<int>() ?? 0;
            if (!Is2xx(status.ToString())) continue;

            // Fields present as keys in response body content
            var bodyContent = response["body"]?["content"]?.AsObject();
            if (bodyContent is not null)
            {
                foreach (var (fieldName, _) in bodyContent)
                    covered.Add(fieldName);
            }

            // Fields declared in matchingRules.body as "$.fieldName"
            var matchingRulesBody = response["matchingRules"]?["body"]?.AsObject();
            if (matchingRulesBody is not null)
            {
                foreach (var (key, _) in matchingRulesBody)
                {
                    // key looks like "$.fieldName" — strip "$."
                    if (key.StartsWith("$."))
                        covered.Add(key[2..]);
                }
            }
        }

        return covered;
    }

    /// <summary>
    /// Resolves a <c>$ref</c> pointer such as
    /// <c>#/components/schemas/UpdateDeviceInformationResponse</c>
    /// by walking the swagger document. Returns the node as-is if no
    /// <c>$ref</c> is present.
    /// </summary>
    private static JsonNode? ResolveRef(JsonNode schema, JsonNode root)
    {
        var refValue = schema["$ref"]?.GetValue<string>();
        if (refValue is null) return schema;

        // Only handle local JSON Pointer refs (#/...)
        if (!refValue.StartsWith("#/")) return schema;

        var parts   = refValue[2..].Split('/');
        JsonNode? node = root;
        foreach (var part in parts)
        {
            node = node?[part];
            if (node is null) return null;
        }
        return node;
    }

    private static bool Is2xx(string statusCode) =>
        statusCode.StartsWith("2") || statusCode == "default";

    private static bool IsHttpVerb(string method) =>
        method is "get" or "post" or "put" or "patch" or "delete" or "head" or "options";

    private static bool PathsMatch(string pactPath, string swaggerPath)
    {
        var cleanPact    = pactPath.Split('?')[0].TrimEnd('/');
        var cleanSwagger = swaggerPath.TrimEnd('/');
        return string.Equals(cleanPact, cleanSwagger, StringComparison.OrdinalIgnoreCase);
    }

    private static List<ConsumerRegistryEntry> LoadConsumerRegistry()
    {
        if (!File.Exists(PactConstants.ConsumersRegistryPath))
            return [];

        try
        {
            var json = File.ReadAllText(PactConstants.ConsumersRegistryPath);
            var doc  = JsonSerializer.Deserialize<ConsumerRegistry>(json,
                new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
            return doc?.Consumers ?? [];
        }
        catch
        {
            return [];
        }
    }

    private sealed record ConsumerRegistry(List<ConsumerRegistryEntry> Consumers);

    private sealed record ConsumerRegistryEntry(
        string Name,
        string Team,
        string Contact,
        string Slack);
}
