using System.Text;
using System.Text.Json;

namespace SwaggerPactGenerator;

/// <summary>
/// Generates a Markdown consumer notification report listing which teams
/// need to update their pact contracts when new swagger endpoints are detected.
///
/// Written to <c>contracts/consumer-notification.md</c> by default.
/// </summary>
public sealed class ConsumerNotificationReport
{
    public async Task WriteReportAsync(
        string                        reportPath,
        List<ApiOperation>            uncoveredOps,
        string?                       consumersRegistryPath = null,
        List<SchemaDriftOperation>?   drifted               = null)
    {
        var consumers = LoadConsumerRegistry(consumersRegistryPath);
        var sb        = new StringBuilder();

        sb.AppendLine("# DeviceApi — Contract Change Notification");
        sb.AppendLine();
        sb.AppendLine($"> Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC");
        sb.AppendLine();
        sb.AppendLine("## Summary");
        sb.AppendLine();
        sb.AppendLine($"The DeviceApi swagger has **{uncoveredOps.Count} new or uncovered endpoint(s)** and **{drifted?.Count ?? 0} schema drift(s)** that require consumer pact test updates.");
        sb.AppendLine();

        if (uncoveredOps.Count > 0)
        {
            sb.AppendLine("## Uncovered Endpoints (new stubs generated)");
            sb.AppendLine();
            sb.AppendLine("| Method | Path | Summary |");
            sb.AppendLine("|--------|------|---------|");

            foreach (var op in uncoveredOps)
                sb.AppendLine($"| `{op.Method.ToUpper()}` | `{op.Path}` | {op.Summary ?? "-"} |");

            sb.AppendLine();
        }

        if (drifted?.Count > 0)
        {
            sb.AppendLine("## Schema Drift on Covered Endpoints");
            sb.AppendLine();
            sb.AppendLine("These endpoints are already covered by pact interactions, but their request body schema has changed.");
            sb.AppendLine("A `*.SchemaDrift.Generated.cs` file has been placed in `Generated/` with the full diff and instructions.");
            sb.AppendLine();
            sb.AppendLine("| Method | Path | Added Fields | Removed Fields |");
            sb.AppendLine("|--------|------|-------------|----------------|");

            foreach (var d in drifted)
            {
                var added   = d.AddedFields.Count   > 0 ? string.Join(", ", d.AddedFields.Select(f => $"`{f}`"))   : "-";
                var removed = d.RemovedFields.Count > 0 ? string.Join(", ", d.RemovedFields.Select(f => $"`{f}`")) : "-";
                sb.AppendLine($"| `{d.SwaggerOperation.Method.ToUpper()}` | `{d.SwaggerOperation.Path}` | {added} | {removed} |");
            }

            sb.AppendLine();
        }

        if (consumers.Count > 0)
        {
            sb.AppendLine("## Consumer Teams to Notify");
            sb.AppendLine();
            sb.AppendLine("Please notify the following teams and ask them to update their pact contracts:");
            sb.AppendLine();

            foreach (var consumer in consumers)
            {
                sb.AppendLine($"### {consumer.Name} ({consumer.Team})");
                sb.AppendLine();
                sb.AppendLine($"- **Email**: {consumer.Contact}");
                sb.AppendLine($"- **Slack**: {consumer.Slack}");
                sb.AppendLine($"- **Pact file**: `contracts/{consumer.PactFile}`");
                sb.AppendLine();
            }
        }
        else
        {
            sb.AppendLine("## Consumer Teams");
            sb.AppendLine();
            sb.AppendLine("> No consumers registered. Add entries to `contracts/consumers.json`.");
            sb.AppendLine();
        }

        sb.AppendLine("## Action Required");
        sb.AppendLine();
        sb.AppendLine("1. **Review generated stubs** in `tests/DeviceApi.Consumer.Tests/Generated/`.");
        sb.AppendLine("2. **Fill in** the `TODO` sections (request payload, response assertions).");
        sb.AppendLine("3. **Move** completed tests to `tests/DeviceApi.Consumer.Tests/Contracts/`.");
        sb.AppendLine("4. **Re-run** `run-pact-tests.ps1` to regenerate the pact file and verify the provider.");
        sb.AppendLine("5. **Update baseline**: `run-pact-tests.ps1 --update-baseline`");
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine("*This file is auto-generated by SwaggerPactGenerator. Do not hand-edit.*");

        await File.WriteAllTextAsync(reportPath, sb.ToString(), Encoding.UTF8);
    }

    private static List<ConsumerEntry> LoadConsumerRegistry(string? path)
    {
        if (string.IsNullOrEmpty(path) || !File.Exists(path))
            return [];

        try
        {
            var json = File.ReadAllText(path);
            var doc  = JsonSerializer.Deserialize<ConsumerRegistry>(json,
                new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
            return doc?.Consumers ?? [];
        }
        catch
        {
            return [];
        }
    }

    private sealed record ConsumerRegistry(List<ConsumerEntry> Consumers);
    private sealed record ConsumerEntry(string Name, string Team, string Contact, string Slack, string PactFile);
}
