using System.Text;

namespace SwaggerPactGenerator;

/// <summary>
/// Generates skeleton PactNet V4 consumer test classes from
/// <see cref="ApiOperation"/> descriptors.
///
/// Output is a compilable C# file placed in the consumer project's
/// <c>Generated/</c> folder.  The consumer team fills in the
/// TODO sections and moves the file to <c>Contracts/</c>.
/// </summary>
public sealed class ConsumerTestGenerator
{
    private const string ConsumerNamespace = "DeviceApi.Consumer.Tests";
    private const string ConsumerName      = "DeviceApi-Consumer";
    private const string ProviderName      = "DeviceApi";

    /// <summary>
    /// Generates a skeleton consumer test stub for the given operation and
    /// writes it to <paramref name="outputDir"/>.
    /// </summary>
    /// <returns>The absolute path of the generated file.</returns>
    public string GenerateStub(ApiOperation op, string outputDir)
    {
        var className = BuildClassName(op);
        var fileName  = $"{className}.Generated.cs";
        var filePath  = Path.Combine(outputDir, fileName);

        // Don't overwrite if already exists — consumer may have started editing it.
        if (File.Exists(filePath))
        {
            Console.WriteLine($"[SKIP] Stub already exists, skipping: {fileName}");
            return filePath;
        }

        var code = BuildClassCode(op, className);
        File.WriteAllText(filePath, code, Encoding.UTF8);
        return filePath;
    }

    // ── Code generation ───────────────────────────────────────────────────────

    private static string BuildClassCode(ApiOperation op, string className)
    {
        var method       = op.Method.ToUpperInvariant();
        var path         = op.Path;
        var summary      = op.Summary ?? $"{method} {path}";
        var responseCodes = op.Responses ?? new Dictionary<string, string> { ["200"] = "Success" };

        var sb = new StringBuilder();
        sb.AppendLine("// ┌──────────────────────────────────────────────────────────────────────┐");
        sb.AppendLine("// │  AUTO-GENERATED by SwaggerPactGenerator — DO NOT HAND-EDIT          │");
        sb.AppendLine("// │                                                                      │");
        sb.AppendLine($"// │  Endpoint : {method,-8} {path,-55}  │");
        sb.AppendLine($"// │  Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC{string.Empty,-39}  │");
        sb.AppendLine("// │                                                                      │");
        sb.AppendLine("// │  Steps for the consumer team:                                        │");
        sb.AppendLine("// │   1. Fill in the TODO sections below.                                │");
        sb.AppendLine("// │   2. Move this file to Contracts/ once assertions are complete.      │");
        sb.AppendLine("// │   3. Run run-pact-tests.ps1 to verify against the provider.          │");
        sb.AppendLine("// └──────────────────────────────────────────────────────────────────────┘");
        sb.AppendLine();
        sb.AppendLine("using System.Net;");
        sb.AppendLine("using System.Net.Http.Json;");
        sb.AppendLine("using FluentAssertions;");
        sb.AppendLine("using PactNet;");
        sb.AppendLine("using PactNet.Matchers;");
        sb.AppendLine($"using {ConsumerNamespace}.Fixtures;");
        sb.AppendLine("using Xunit;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ConsumerNamespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// AUTO-GENERATED skeleton consumer tests for: {method} {path}");
        sb.AppendLine($"/// Summary: {summary}");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed class {className} : IClassFixture<ConsumerPactFixture>");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly ConsumerPactFixture _fixture;");
        sb.AppendLine($"    private const string Endpoint = \"{path}\";");
        sb.AppendLine();
        sb.AppendLine($"    public {className}(ConsumerPactFixture fixture) => _fixture = fixture;");
        sb.AppendLine();

        // Generate one test method per response code
        foreach (var (statusCode, description) in responseCodes)
        {
            var methodName = $"{BuildMethodName(op)}_{description.Replace(" ", "_").Replace(".", "")}_Returns{statusCode}";
            var httpMethod = ToCSharpHttpMethod(op.Method);

            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// TODO: Verify the consumer contract for {method} {path} → {statusCode} {description}");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [Fact]");
            sb.AppendLine($"    public async Task {SanitiseName(methodName)}()");
            sb.AppendLine("    {");
            sb.AppendLine("        var pact = _fixture.CreateBuilder();");
            sb.AppendLine();
            sb.AppendLine("        pact");
            sb.AppendLine($"            .UponReceiving(\"TODO: describe the consumer scenario for {method} {path}\")");
            sb.AppendLine($"            .WithRequest({httpMethod}, Endpoint)");

            if (op.Method.Equals("post", StringComparison.OrdinalIgnoreCase)
                || op.Method.Equals("put", StringComparison.OrdinalIgnoreCase)
                || op.Method.Equals("patch", StringComparison.OrdinalIgnoreCase))
            {
                sb.AppendLine("            .WithHeader(\"Content-Type\", \"application/json; charset=utf-8\")");
                sb.AppendLine("            .WithJsonBody(new");
                sb.AppendLine("            {");
                sb.AppendLine("                // TODO: populate request body fields");
                sb.AppendLine("            })");
            }

            sb.AppendLine("            .WillRespond()");
            sb.AppendLine($"            .WithStatus(HttpStatusCode.{MapStatusCode(statusCode)});");

            sb.AppendLine();
            sb.AppendLine("        await pact.VerifyAsync(async ctx =>");
            sb.AppendLine("        {");
            sb.AppendLine("            using var client = new HttpClient { BaseAddress = ctx.MockServerUri };");

            if (op.Method.Equals("get", StringComparison.OrdinalIgnoreCase)
                || op.Method.Equals("delete", StringComparison.OrdinalIgnoreCase))
            {
                sb.AppendLine($"            var response = await client.{ToCSharpClientMethod(op.Method)}(Endpoint);");
            }
            else
            {
                sb.AppendLine("            // TODO: replace with actual request payload");
                sb.AppendLine("            var payload  = new { /* TODO */ };");
                sb.AppendLine($"            var response = await client.PostAsJsonAsync(Endpoint, payload);");
            }
            sb.AppendLine();
            sb.AppendLine($"            response.StatusCode.Should().Be(HttpStatusCode.{MapStatusCode(statusCode)});");
            sb.AppendLine("            // TODO: add response body assertions");
            sb.AppendLine("        });");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // ── Naming helpers ─────────────────────────────────────────────────────────

    private static string BuildClassName(ApiOperation op)
    {
        var segment = op.Path
            .Split('/', StringSplitOptions.RemoveEmptyEntries)
            .LastOrDefault() ?? "Unknown";
        var verb    = ToPascal(op.Method);
        return $"{SanitiseName(segment)}_{verb}ConsumerTests";
    }

    private static string BuildMethodName(ApiOperation op)
    {
        var segment = op.Path
            .Split('/', StringSplitOptions.RemoveEmptyEntries)
            .LastOrDefault() ?? "Unknown";
        return $"{SanitiseName(segment)}_{ToPascal(op.Method)}";
    }

    private static string ToPascal(string s) =>
        char.ToUpperInvariant(s[0]) + s[1..].ToLowerInvariant();

    private static string SanitiseName(string s) =>
        new string(s.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray());

    private static string ToCSharpHttpMethod(string method) => method.ToUpperInvariant() switch
    {
        "GET"    => "HttpMethod.Get",
        "POST"   => "HttpMethod.Post",
        "PUT"    => "HttpMethod.Put",
        "PATCH"  => "HttpMethod.Patch",
        "DELETE" => "HttpMethod.Delete",
        _        => $"new HttpMethod(\"{method.ToUpperInvariant()}\")"
    };

    private static string ToCSharpClientMethod(string method) => method.ToUpperInvariant() switch
    {
        "GET"    => "GetAsync",
        "DELETE" => "DeleteAsync",
        _        => "SendAsync"
    };

    private static string MapStatusCode(string code) => code switch
    {
        "200" => "OK",
        "201" => "Created",
        "204" => "NoContent",
        "400" => "BadRequest",
        "401" => "Unauthorized",
        "403" => "Forbidden",
        "404" => "NotFound",
        "409" => "Conflict",
        "500" => "InternalServerError",
        _     => code
    };
}
